# Generated by Django 2.2 on 2020-06-20 02:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(55)])),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
